// https://github.com/eslint-community/eslint-plugin-n

export default {
  'callback-return': 1,
  'exports-style': 0,
  'file-extension-in-import': 0,
  'global-require': 0,
  'handle-callback-err': 0,
  'hashbang': 2,
  'no-callback-literal': 0,
  'no-deprecated-api': 2,
  'no-exports-assign': 2,
  'no-extraneous-import': 0,
  'no-extraneous-require': 0,
  'no-missing-import': 0,
  'no-missing-require': 0,
  'no-mixed-requires': [2, { allowCall: true, grouping: true }],
  'no-new-require': 2,
  'no-path-concat': 2,
  'no-process-env': 0,
  'no-process-exit': 0, // TODO: Revisit this rule
  'no-restricted-import': 0,
  'no-restricted-require': 0,
  'no-sync': 0,
  'no-unpublished-bin': 2,
  'no-unpublished-import': 0,
  'no-unpublished-require': 0,
  'no-unsupported-features/es-builtins': 2,
  'no-unsupported-features/es-syntax': 2,
  'no-unsupported-features/node-builtins': 2,
  'prefer-global/buffer': 2,
  'prefer-global/console': 2,
  'prefer-global/process': 2,
  'prefer-global/text-decoder': 2,
  'prefer-global/text-encoder': 2,
  'prefer-global/url': 2,
  'prefer-global/url-search-params': 2,
  'prefer-node-protocol': 2,
  'prefer-promises/dns': 2,
  'prefer-promises/fs': 2,
  'process-exit-as-throw': 0,
}
