// https://github.com/eslint-community/eslint-plugin-n

export default {
  'n/callback-return': 1,
  'n/exports-style': 0,
  'n/file-extension-in-import': 0,
  'n/global-require': 0,
  'n/handle-callback-err': 0,
  'n/hashbang': 2,
  'n/no-callback-literal': 0,
  'n/no-deprecated-api': 2,
  'n/no-exports-assign': 2,
  'n/no-extraneous-import': 0,
  'n/no-extraneous-require': 0,
  'n/no-missing-import': 0,
  'n/no-missing-require': 0,
  'n/no-mixed-requires': [2, { allowCall: true, grouping: true }],
  'n/no-new-require': 2,
  'n/no-path-concat': 2,
  'n/no-process-env': 0,
  'n/no-process-exit': 0, // TODO: Revisit this rule
  'n/no-restricted-import': 0,
  'n/no-restricted-require': 0,
  'n/no-sync': 0,
  'n/no-unpublished-bin': 2,
  'n/no-unpublished-import': 0,
  'n/no-unpublished-require': 0,
  'n/no-unsupported-features/es-builtins': 2,
  'n/no-unsupported-features/es-syntax': 2,
  'n/no-unsupported-features/node-builtins': 2,
  'n/prefer-global/buffer': 2,
  'n/prefer-global/console': 2,
  'n/prefer-global/process': 2,
  'n/prefer-global/text-decoder': 2,
  'n/prefer-global/text-encoder': 2,
  'n/prefer-global/url': 2,
  'n/prefer-global/url-search-params': 2,
  'n/prefer-node-protocol': 2,
  'n/prefer-promises/dns': 2,
  'n/prefer-promises/fs': 2,
  'n/process-exit-as-throw': 0,
}
